version: "3.9"

services:
  pgs.template-placeholder-bot:
#    image: harlok13/pgs.template-placeholder-bot:latest
    build:
      context: .
      dockerfile: PGS.TemplatePlaceholderBot/Dockerfile
    volumes:
      - ./PGS.TemplatePlaceholderBot/files:/app/files
    environment:
      - ENVIRONMENT=Development
      - TOKEN=${TOKEN}
      - VOLUME_PATH=${VOLUME_PATH}
    stdin_open: true
    tty: true
    env_file:
      - ./PGS.TemplatePlaceholderBot/.env
        
  pgs.minio-storage:
    image: bitnami/minio:2024.2.14
    container_name: pgs.minio-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: pgs_minio
      MINIO_ROOT_PASSWORD: pgs_minio
    volumes:
      - ./PGS.TemplatePlaceholderBot/minio-data:/bitnami/minio/data
