version: "3.9"

services:
  pgs.template-placeholder-bot:
#    image: harlok13/pgs.template-placeholder-bot:latest
    build:
      context: .
      dockerfile: PGS.TemplatePlaceholderBot/Dockerfile
    volumes:
      - ./PGS.TemplatePlaceholderBot/files:/app/files
    environment:
      - ENVIRONMENT=Development
      - TOKEN=${TOKEN}
      - VOLUME_PATH=${VOLUME_PATH}
    stdin_open: true
    tty: true
    env_file:
      - ./PGS.TemplatePlaceholderBot/.env
